version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8082:80" # Host:Container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_PORT: 3306
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    # depends_on:
    #   - backend

volumes:
  mysqldata:
